name: Deploy Workflow

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      runs-on: self-hosted 
  
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0


    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Plan
      run: terraform plan -no-color

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

    