name: Deploy Workflow

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Plan
      run: terraform plan -no-color

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

    